name: Build image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Setup Oracle Cloud Infrastructure (OCI) Credentials
      - name: Setup OCI Credentials
        env:
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
          OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
        run: |
          echo "$OCI_USERNAME"
          echo $OCI_AUTH_TOKEN | docker login phx.ocir.io -u "$OCI_USERNAME" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: axsgshhbf0lb/luma-bullq-exporter:latest
          # cache-from: type=gha
          # cache-to: type=gha,mode=max